service:
  name: plantuml-encoder

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  encode:
    memorySize: 128 # optional, in MB, default is 1024
    handler: handler.encodeHandler
    events:
      - http:
          method: post
          path: encode
